version: "3.8"
services:
  app:
    build: .
    container_name: pickbus-app
    ports:
    - "8080:8080"
    depends_on:
    - mysql
    - redis
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - SPRING_REDIS_HOST=redis
    - SPRING_REDIS_PORT=6379
    - JWT_SECRET=${JWT_SECRET}
    - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
    - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
    - ENCRYPT_EMAIL_SECRET=${ENCRYPT_EMAIL_SECRET}
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    - BUSAN_API_KEY=${BUSAN_API_KEY}

  mysql:
    image: mysql:8
    container_name: pickbus-mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - TZ=Asia/Seoul
    ports:
    - "33066:3306"
    volumes:
      - mysql-data:/var/lib/mysql


  redis:
    image: redis:7
    container_name: pickbus-redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
    - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: pickbus-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: pickbus-kibana
    ports:
       - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
      image: docker.elastic.co/logstash/logstash:8.13.0
      container_name: pickbus-logstash
      ports:
        - "5044:5044"
      volumes:
        - ./logstash/pickbus.conf:/usr/share/logstash/pipeline/logstash.conf
      depends_on:
        - elasticsearch

  filebeat:
      image: docker.elastic.co/beats/filebeat:8.13.0
      container_name: pickbus-filebeat
      user: root
      volumes:
        - ./logs:/logs
        - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      depends_on:
        - logstash


volumes:
  mysql-data: