spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      password: ${REDIS_PASSWORD}
  cache:
    type: redis
    redis:
      time-to-live: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}

encrypt:
  email:
    secret: ${ENCRYPT_EMAIL_SECRET}

busan:
  api:
    key: ${BUSAN_API_KEY}


server:
  port: 8080
  servlet:
    context-path: /